Fix EmptySelectError crash on Proposals tab pane
Error was:
```
EmptySelectError: Select options cannot be empty if selection can't be blank.
```

It was caused because ORDER_DIRECTIONS alias was refering to
get_args(OrderDirections) where OrderDirections was `type`.
Aliases annotated with `type` cannot be used in runtime.
Instead, corresponding finals from
clive.__private.core.constants.data_retrieval
were used.