Fix crash on cart items deleting
There seems to be an race when item deletion occurs,
because previously it was not awaited and textual
seemed to render LoadingIndicator when it was unmounted yet.

This caused in:
AttributeError: 'LoadingIndicator' object has no attribute '_start_time'