Set custom format for poetry-dynamic-versioning
This is because previous setting dissallowed publishing to the
official PyPI.

When version was "1.27.5.0+f9eca07", PyPI responded with:
```
HTTP Error 400: '1.27.5.0+f9eca07' is an invalid value for Version.
Error: Can't use PEP 440 local versions. See
https://packaging.python.org/specifications/core-metadata for more
information. | b"<html>\n <head>\n  <title>400 '1.27.5.0+f9eca07' is an
invalid value for Version. Error: Can't use PEP 440 local versions. See
https://packaging.python.org/specifications/core-metadata for more
information.\n \n <body>\n  <h1>400 '1.27.5.0+f9eca07' is an invalid
value for Version. Error: Can't use PEP 440 local versions. See
https://packaging.python.org/specifications/core-metadata for more
information.\n  The server could not comply with the request since it is
either malformed or otherwise
incorrect.<br/><br/>\n&#x27;1.27.5.0+f9eca07&#x27; is an invalid value
for Version. Error: Can&#x27;t use PEP 440 local versions. See
https://packaging.python.org/specifications/core-metadata for more
information.\n\n\n \n"
```