Fix issue with FileNotFoundError
When default.beekeeper.path is set to "./beekeeper"
there was an error even if path existed:
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('beekeeper')