Change the default of run_async "mouse" parameter to True
We only use clive TUI with mouse. Also while not set, app can't be
launched because throws error like:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 4: invalid start byte