Fix for stale gdpo used in UpdateNodeData processing
This issue was observed with
`clive list balances` comamnd
when it failes with:

WaxOperationFailedError: 10 assert_exception: Assert Exception
now >= last_update_time:
    {}
    manabar.hpp:46 regenerate_mana

becasue we'were taking the `now` from gdpo which was
received in another (previous) api call so it might be
fetched for previous block.