Workaround for wax assertion error while calculating manabar related things
When using:
  - calculate_current_manabar_value
  - calculate_manabar_full_regeneration_time

we observed wax error due to `now` being older than
`last_update`.

Example error:
```
WaxOperationFailedError: 10 assert_exception: Assert Exception
now >= last_update_time
```

That's caused because hived answers to batch query
in a way, blockchain state between different API calls
in that batch could change.
So we got older head block time in gdpo received by
`get_dynamic_global_properties` API
than actually was stored in rc_manabar.last_update_time taken from
`find_rc_accounts` API.